/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginform;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

public class AdminFrame extends javax.swing.JFrame {

    Admin admin ;
    private Connection connection;
    private ArrayList<Medicament> medicaments;
    private ArrayList<Medicament> snapshot;
    
    
    public AdminFrame(Admin adm) {
        
        admin=adm;
        initComponents();
        aficherTabel();
        connection=MyConnection.getConnection();
    }
    public AdminFrame() {
        
        
        initComponents();

    }
    
    
    public void aficherTabel(){
        
        DefaultTableModel tblModel = (DefaultTableModel) MedicTable.getModel();
        tblModel.setRowCount(0);
        
        try {
            snapshot=MyConnection.databaseSnapshot();
            for(Medicament medicament:snapshot){
                String data []= {medicament.getName(),String.valueOf(medicament.getQuantite()),String.valueOf(medicament.getPrix())};
                tblModel.addRow(data);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Un probleme a survenu");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MedicTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        medicNameField = new javax.swing.JTextField();
        QuantiteFiled = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prixFiled = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        NvMedicamentPanel = new javax.swing.JPanel();
        nouveauMedicamentLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacie");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        MedicTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicament", "Quantité", "Prix"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MedicTable.setAlignmentY(1.0F);
        MedicTable.setRowHeight(40);
        MedicTable.setRowMargin(5);
        MedicTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MedicTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Medicament name :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Quantité :");

        medicNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                medicNameFieldFocusGained(evt);
            }
        });
        medicNameField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                medicNameFieldInputMethodTextChanged(evt);
            }
        });
        medicNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicNameFieldActionPerformed(evt);
            }
        });

        QuantiteFiled.setText("1");
        QuantiteFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantiteFiledActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Prix :");

        prixFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixFiledActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NvMedicamentPanel.setBackground(new java.awt.Color(0, 0, 102));
        NvMedicamentPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NvMedicamentPanelKeyPressed(evt);
            }
        });

        nouveauMedicamentLabel.setBackground(new java.awt.Color(153, 255, 255));
        nouveauMedicamentLabel.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        nouveauMedicamentLabel.setForeground(new java.awt.Color(255, 255, 255));
        nouveauMedicamentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nouveauMedicamentLabel.setText("Ajouter un nouveau Medicament");
        nouveauMedicamentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nouveauMedicamentLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout NvMedicamentPanelLayout = new javax.swing.GroupLayout(NvMedicamentPanel);
        NvMedicamentPanel.setLayout(NvMedicamentPanelLayout);
        NvMedicamentPanelLayout.setHorizontalGroup(
            NvMedicamentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NvMedicamentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nouveauMedicamentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        NvMedicamentPanelLayout.setVerticalGroup(
            NvMedicamentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NvMedicamentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nouveauMedicamentLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 139, Short.MAX_VALUE)
                        .addComponent(NvMedicamentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(QuantiteFiled, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                            .addComponent(medicNameField)
                                            .addComponent(prixFiled)))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(medicNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(QuantiteFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prixFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NvMedicamentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 600));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\1.PNG")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MedicTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicTableMouseClicked
        String medicamentName=MedicTable.getModel().getValueAt(MedicTable.getSelectedRow(), 0).toString();
        String medicamentQuantite=MedicTable.getModel().getValueAt(MedicTable.getSelectedRow(), 1).toString();
        String medicamentPrix = MedicTable.getModel().getValueAt(MedicTable.getSelectedRow(), 2).toString();
        medicNameField.setText(medicamentName);
        QuantiteFiled.setText(medicamentQuantite);
        prixFiled.setText(medicamentPrix);
    }//GEN-LAST:event_MedicTableMouseClicked

    private void medicNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_medicNameFieldFocusGained

        medicNameField.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTabel();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTabel();

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateTabel();

            }

            public void updateTabel(){
                String medicName = medicNameField.getText();
                int quantite = Integer.parseInt(QuantiteFiled.getText());

                DefaultTableModel tblModel = (DefaultTableModel) MedicTable.getModel();

                tblModel.setRowCount(0);

                medicaments=MyConnection.searchInData(medicName,MyConnection.getSnapshot());

                for(Medicament medicament:medicaments){
                    String data []= {medicament.getName(),String.valueOf(medicament.getQuantite()),String.valueOf(medicament.getPrix())};
                    tblModel.addRow(data);
                }
                if(medicaments.size()==1){
                    QuantiteFiled.setText(String.valueOf(medicaments.get(0).getQuantite()));
                    prixFiled.setText(String.valueOf(medicaments.get(0).getPrix()));
                }

            }

        });

    }//GEN-LAST:event_medicNameFieldFocusGained

    private void medicNameFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_medicNameFieldInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_medicNameFieldInputMethodTextChanged

    private void medicNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicNameFieldActionPerformed

    private void QuantiteFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantiteFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantiteFiledActionPerformed

    private void prixFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixFiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixFiledActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String medicamentName = medicNameField.getText();
        String medicamentQuantite=QuantiteFiled.getText();
        String medicamentPrix=prixFiled.getText();
        
        String query="UPDATE `medicament` SET `QUANTITE`=?,`PRIX`=? WHERE `NAME`=?";
        
        try {
            PreparedStatement ps=MyConnection.getConnection().prepareStatement(query);
                 ps.setString(1,medicamentQuantite);
                 ps.setString(2,medicamentPrix);
                 ps.setString(3,medicamentName);
                 ps.executeUpdate();
                aficherTabel();
                JOptionPane.showMessageDialog(null, "Medicament modifier");
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NvMedicamentPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NvMedicamentPanelKeyPressed
        
        
        
        
    }//GEN-LAST:event_NvMedicamentPanelKeyPressed

    private void nouveauMedicamentLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nouveauMedicamentLabelMousePressed
        nouveauMedicamentFrame frame = new nouveauMedicamentFrame(admin);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nouveauMedicamentLabelMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    LoginForm frame = new LoginForm();
        frame.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MedicTable;
    private javax.swing.JPanel NvMedicamentPanel;
    private javax.swing.JTextField QuantiteFiled;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medicNameField;
    private javax.swing.JLabel nouveauMedicamentLabel;
    private javax.swing.JTextField prixFiled;
    // End of variables declaration//GEN-END:variables
}
